/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#FEE2E5',
          100: '#FBBFC6',
          200: '#F4808F',
          300: '#EE5065',
          400: '#E63D52',
          500: '#D4192F',
          600: '#C8102E',
          700: '#A00B24',
          800: '#75071A',
          900: '#4D0512',
        },
        steel: {
          50:  '#F5F5F5',
          100: '#E8E8E8',
          200: '#D1D1D1',
          300: '#B0B0B0',
          400: '#8C8C8C',
          500: '#6B7280',
          600: '#4B5563',
          700: '#374151',
          800: '#1F2937',
          900: '#1A1A1A',
        },
        accent: {
          DEFAULT: '#F5C400',
          light:   '#FFF3CC',
        },
        // Material Design 3 tokens
        'primary':                  '#93000b',
        'on-primary':               '#ffffff',
        'primary-container':        '#b91c1c',
        'on-primary-container':     '#ffcdc7',
        'secondary':                '#575e70',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#d9dff5',
        'on-secondary-container':   '#5c6274',
        'tertiary':                 '#00497f',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#0061a6',
        'on-tertiary-container':    '#c1dbff',
        'on-surface':               '#151c27',
        'on-background':            '#151c27',
        'surface-variant':          '#dce2f3',
        'on-surface-variant':       '#5b403d',
        'outline':                  '#8f6f6c',
        'outline-variant':          '#e4beb9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f0f3ff',
        'surface-container':        '#e7eefe',
        'surface-container-high':   '#e2e8f8',
        'surface-container-highest':'#dce2f3',
        'inverse-surface':          '#2a313d',
        'inverse-on-surface':       '#ebf1ff',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'background':               '#f9f9ff',
        'surface':                  '#f9f9ff',
        // Warm design system
        cream:  { DEFAULT: '#FAF8F5', 2: '#F0EDE8' },
        paper:  '#FFFFFF',
        ink:    { DEFAULT: '#241E18', 2: '#3A312A' },
        muted:  { DEFAULT: '#7A6E62', 2: '#A89B8C' },
        hair:   { DEFAULT: '#E8E1D6', 2: '#DCD2C2' },
        terra:  { DEFAULT: '#B22234', deep: '#8C1A28', soft: '#F5DCDF' },
        navy:   { DEFAULT: '#002868', deep: '#001A47', soft: '#DDE4EF' },
        'warm-ok':   { DEFAULT: '#047857', bg: '#D1FAE5' },
        'warm-warn': { DEFAULT: '#B45309', bg: '#FEF3C7' },
        'warm-crit': { DEFAULT: '#B22234', bg: '#FEE2E2' },
      },
      fontFamily: {
        sans:         ['"Nunito Sans"', 'system-ui', 'sans-serif'],
        serif:        ['"Nunito"', 'system-ui', 'sans-serif'],
        mono:         ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        nunito:       ['"Nunito"', 'system-ui', 'sans-serif'],
        'nunito-sans':['"Nunito Sans"', 'system-ui', 'sans-serif'],
        hanken:       ['"Nunito Sans"', 'system-ui', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg':  ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md':  ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm':  ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md':      ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':      ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-mono':   ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'table-header': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-once': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'slide-in': {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'pulse-crit': {
          '0%, 100%': { boxShadow: '0 4px 12px -3px rgba(178,34,52,0.45), 0 0 0 0 rgba(178,34,52,0.4), inset 0 0 0 1px rgba(255,255,255,0.18)' },
          '50%':       { boxShadow: '0 4px 12px -3px rgba(178,34,52,0.45), 0 0 0 8px rgba(178,34,52,0), inset 0 0 0 1px rgba(255,255,255,0.18)' },
        },
        // ─── Charts ────────────────────────────────────────────────────
        'chart-grow': {
          '0%':   { transform: 'scaleY(0)' },
          '100%': { transform: 'scaleY(1)' },
        },
        'chart-fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'chart-draw': {
          '0%':   { strokeDashoffset: 'var(--chart-len, 1000)' },
          '100%': { strokeDashoffset: '0' },
        },
        'chart-gauge-fill': {
          '0%':   { strokeDashoffset: 'var(--chart-len, 1000)' },
          '100%': { strokeDashoffset: 'var(--chart-end, 0)' },
        },
      },
      spacing: {
        'card-padding':       '16px',
        'container-margin':   '24px',
        'gutter':             '16px',
        'table-cell-padding': '12px',
      },
      animation: {
        'pulse-once': 'pulse-once 0.6s ease-in-out 1',
        'slide-in':   'slide-in 0.3s ease-out 1',
        'pulse-crit': 'pulse-crit 2.4s ease-in-out infinite',
        'chart-grow':         'chart-grow 600ms ease-out 1',
        'chart-fade-in':      'chart-fade-in 500ms ease-out 1',
        'chart-draw':         'chart-draw 900ms ease-out 1',
        'chart-gauge-fill':   'chart-gauge-fill 1100ms ease-out 1',
      },
    },
  },
  plugins: [],
}
